// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../infra/entities/group_entity/group_entity.dart';
import '../../infra/entities/network_group_entity/network_group_entity.dart';
import '../../infra/entities/transaction_entity/ethereum_transaction_entity.dart';
import '../../infra/entities/transaction_entity/solana_transaction_entity.dart';
import '../../infra/entities/vault_entity/vault_entity.dart';
import '../../infra/entities/wallet_entity/wallet_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6130969521279919079),
    name: 'EthereumTransactionEntity',
    lastPropertyId: const obx_int.IdUid(13, 558533052377856057),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6227111190251521279),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3365044417320239320),
        name: 'walletId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 7605396361057136729),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 647070494511078914),
        name: 'creationDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5997183312923947244),
        name: 'dbSignDataType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5932959644603175767),
        name: 'amount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5624880723496626234),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7176203173203028614),
        name: 'contractAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4786966385202293391),
        name: 'senderAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2688948152493146340),
        name: 'recipientAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9207153379519480554),
        name: 'signature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8680597079711010156),
        name: 'signDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3565599128059893092),
        name: 'fee',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 558533052377856057),
        name: 'functionData',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6959257034095921460),
    name: 'GroupEntity',
    lastPropertyId: const obx_int.IdUid(5, 3226495466728930210),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8995776965330489447),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7347242605594925573),
        name: 'pinnedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 813218962268653088),
        name: 'encryptedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8701442630274541630),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3226495466728930210),
        name: 'filesystemPathString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 1125534695622332462),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3371859090537542355),
    name: 'NetworkGroupEntity',
    lastPropertyId: const obx_int.IdUid(7, 4036855640115937034),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 836161657770918637),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 478488359979049903),
        name: 'encryptedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 472116539153928768),
        name: 'pinnedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5707313850238157062),
        name: 'filesystemPathString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7694087767479588904),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4527925771770628132),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4036855640115937034),
        name: 'dbNetworkType',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2420595178599573901),
    name: 'SolanaTransactionEntity',
    lastPropertyId: const obx_int.IdUid(13, 2746248981835962896),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5083710289210834578),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4838610328291379362),
        name: 'walletId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 4637749822139708937),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 390016402075986987),
        name: 'creationDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 528518194551485118),
        name: 'dbSignDataType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5341334567630635909),
        name: 'amount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3306299018127316524),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6372226593539820902),
        name: 'contractAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5010557270348459259),
        name: 'senderAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1045792496409530362),
        name: 'recipientAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7540010245972904655),
        name: 'signature',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8110002860428895468),
        name: 'signDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6852308649364884267),
        name: 'signerAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2746248981835962896),
        name: 'transactionData',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 5777740611729434622),
    name: 'VaultEntity',
    lastPropertyId: const obx_int.IdUid(7, 993057843297678163),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 569624330039722167),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6957721728437087652),
        name: 'encryptedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1185784198547412109),
        name: 'pinnedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1845088090424747428),
        name: 'fingerprint',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 1176475969656295812),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7216106779400935862),
        name: 'index',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 4811492173459783520),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2829346793074253089),
        name: 'filesystemPathString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 7499015055604764041),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 993057843297678163),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5079348458243862348),
    name: 'WalletEntity',
    lastPropertyId: const obx_int.IdUid(7, 808951229166466672),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 757805395957886712),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1839938823472162470),
        name: 'encryptedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3725643217845444500),
        name: 'pinnedBool',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2270148571315479929),
        name: 'address',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7863734322134474927),
        name: 'derivationPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7063663031630315731),
        name: 'filesystemPathString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 3713637070011341925),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 808951229166466672),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 5079348458243862348),
    lastIndexId: const obx_int.IdUid(9, 3713637070011341925),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EthereumTransactionEntity:
        obx_int.EntityDefinition<EthereumTransactionEntity>(
          model: _entities[0],
          toOneRelations: (EthereumTransactionEntity object) => [],
          toManyRelations: (EthereumTransactionEntity object) => {},
          getId: (EthereumTransactionEntity object) => object.id,
          setId: (EthereumTransactionEntity object, int id) {
            object.id = id;
          },
          objectToFB: (EthereumTransactionEntity object, fb.Builder fbb) {
            final creationDateOffset = fbb.writeString(object.creationDate);
            final dbSignDataTypeOffset = object.dbSignDataType == null
                ? null
                : fbb.writeString(object.dbSignDataType!);
            final amountOffset = object.amount == null
                ? null
                : fbb.writeString(object.amount!);
            final messageOffset = object.message == null
                ? null
                : fbb.writeString(object.message!);
            final contractAddressOffset = object.contractAddress == null
                ? null
                : fbb.writeString(object.contractAddress!);
            final senderAddressOffset = object.senderAddress == null
                ? null
                : fbb.writeString(object.senderAddress!);
            final recipientAddressOffset = object.recipientAddress == null
                ? null
                : fbb.writeString(object.recipientAddress!);
            final signatureOffset = object.signature == null
                ? null
                : fbb.writeString(object.signature!);
            final signDateOffset = object.signDate == null
                ? null
                : fbb.writeString(object.signDate!);
            final feeOffset = object.fee == null
                ? null
                : fbb.writeString(object.fee!);
            final functionDataOffset = object.functionData == null
                ? null
                : fbb.writeString(object.functionData!);
            fbb.startTable(14);
            fbb.addInt64(0, object.id);
            fbb.addInt64(1, object.walletId);
            fbb.addOffset(2, creationDateOffset);
            fbb.addOffset(3, dbSignDataTypeOffset);
            fbb.addOffset(4, amountOffset);
            fbb.addOffset(5, messageOffset);
            fbb.addOffset(6, contractAddressOffset);
            fbb.addOffset(7, senderAddressOffset);
            fbb.addOffset(8, recipientAddressOffset);
            fbb.addOffset(9, signatureOffset);
            fbb.addOffset(10, signDateOffset);
            fbb.addOffset(11, feeOffset);
            fbb.addOffset(12, functionDataOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final walletIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              6,
              0,
            );
            final creationDateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final dbSignDataTypeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 10);
            final amountParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 12);
            final messageParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 14);
            final contractAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 16);
            final senderAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 18);
            final recipientAddressParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 20);
            final signatureParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 22);
            final signDateParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 24);
            final feeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 26);
            final functionDataParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 28);
            final object = EthereumTransactionEntity(
              id: idParam,
              walletId: walletIdParam,
              creationDate: creationDateParam,
              dbSignDataType: dbSignDataTypeParam,
              amount: amountParam,
              message: messageParam,
              contractAddress: contractAddressParam,
              senderAddress: senderAddressParam,
              recipientAddress: recipientAddressParam,
              signature: signatureParam,
              signDate: signDateParam,
              fee: feeParam,
              functionData: functionDataParam,
            );

            return object;
          },
        ),
    GroupEntity: obx_int.EntityDefinition<GroupEntity>(
      model: _entities[1],
      toOneRelations: (GroupEntity object) => [],
      toManyRelations: (GroupEntity object) => {},
      getId: (GroupEntity object) => object.id,
      setId: (GroupEntity object, int id) {
        object.id = id;
      },
      objectToFB: (GroupEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final filesystemPathStringOffset = fbb.writeString(
          object.filesystemPathString,
        );
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.pinnedBool);
        fbb.addBool(2, object.encryptedBool);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, filesystemPathStringOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final pinnedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final encryptedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final filesystemPathStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = GroupEntity(
          id: idParam,
          pinnedBool: pinnedBoolParam,
          encryptedBool: encryptedBoolParam,
          name: nameParam,
          filesystemPathString: filesystemPathStringParam,
        );

        return object;
      },
    ),
    NetworkGroupEntity: obx_int.EntityDefinition<NetworkGroupEntity>(
      model: _entities[2],
      toOneRelations: (NetworkGroupEntity object) => [],
      toManyRelations: (NetworkGroupEntity object) => {},
      getId: (NetworkGroupEntity object) => object.id,
      setId: (NetworkGroupEntity object, int id) {
        object.id = id;
      },
      objectToFB: (NetworkGroupEntity object, fb.Builder fbb) {
        final filesystemPathStringOffset = fbb.writeString(
          object.filesystemPathString,
        );
        final nameOffset = fbb.writeString(object.name);
        final dbNetworkTypeOffset = object.dbNetworkType == null
            ? null
            : fbb.writeString(object.dbNetworkType!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.encryptedBool);
        fbb.addBool(2, object.pinnedBool);
        fbb.addOffset(3, filesystemPathStringOffset);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(6, dbNetworkTypeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final encryptedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final pinnedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final filesystemPathStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final dbNetworkTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final object = NetworkGroupEntity(
          id: idParam,
          encryptedBool: encryptedBoolParam,
          pinnedBool: pinnedBoolParam,
          filesystemPathString: filesystemPathStringParam,
          name: nameParam,
          dbNetworkType: dbNetworkTypeParam,
        );

        return object;
      },
    ),
    SolanaTransactionEntity: obx_int.EntityDefinition<SolanaTransactionEntity>(
      model: _entities[3],
      toOneRelations: (SolanaTransactionEntity object) => [],
      toManyRelations: (SolanaTransactionEntity object) => {},
      getId: (SolanaTransactionEntity object) => object.id,
      setId: (SolanaTransactionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SolanaTransactionEntity object, fb.Builder fbb) {
        final creationDateOffset = fbb.writeString(object.creationDate);
        final dbSignDataTypeOffset = object.dbSignDataType == null
            ? null
            : fbb.writeString(object.dbSignDataType!);
        final amountOffset = object.amount == null
            ? null
            : fbb.writeString(object.amount!);
        final messageOffset = object.message == null
            ? null
            : fbb.writeString(object.message!);
        final contractAddressOffset = object.contractAddress == null
            ? null
            : fbb.writeString(object.contractAddress!);
        final senderAddressOffset = object.senderAddress == null
            ? null
            : fbb.writeString(object.senderAddress!);
        final recipientAddressOffset = object.recipientAddress == null
            ? null
            : fbb.writeString(object.recipientAddress!);
        final signatureOffset = object.signature == null
            ? null
            : fbb.writeString(object.signature!);
        final signDateOffset = object.signDate == null
            ? null
            : fbb.writeString(object.signDate!);
        final signerAddressOffset = fbb.writeString(object.signerAddress);
        final transactionDataOffset = object.transactionData == null
            ? null
            : fbb.writeString(object.transactionData!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.walletId);
        fbb.addOffset(2, creationDateOffset);
        fbb.addOffset(3, dbSignDataTypeOffset);
        fbb.addOffset(4, amountOffset);
        fbb.addOffset(5, messageOffset);
        fbb.addOffset(6, contractAddressOffset);
        fbb.addOffset(7, senderAddressOffset);
        fbb.addOffset(8, recipientAddressOffset);
        fbb.addOffset(9, signatureOffset);
        fbb.addOffset(10, signDateOffset);
        fbb.addOffset(11, signerAddressOffset);
        fbb.addOffset(12, transactionDataOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final walletIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final creationDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final signerAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final dbSignDataTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final amountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final contractAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final senderAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final recipientAddressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final signDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final signatureParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final transactionDataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final object = SolanaTransactionEntity(
          id: idParam,
          walletId: walletIdParam,
          creationDate: creationDateParam,
          signerAddress: signerAddressParam,
          dbSignDataType: dbSignDataTypeParam,
          amount: amountParam,
          message: messageParam,
          contractAddress: contractAddressParam,
          senderAddress: senderAddressParam,
          recipientAddress: recipientAddressParam,
          signDate: signDateParam,
          signature: signatureParam,
          transactionData: transactionDataParam,
        );

        return object;
      },
    ),
    VaultEntity: obx_int.EntityDefinition<VaultEntity>(
      model: _entities[4],
      toOneRelations: (VaultEntity object) => [],
      toManyRelations: (VaultEntity object) => {},
      getId: (VaultEntity object) => object.id,
      setId: (VaultEntity object, int id) {
        object.id = id;
      },
      objectToFB: (VaultEntity object, fb.Builder fbb) {
        final fingerprintOffset = fbb.writeString(object.fingerprint);
        final filesystemPathStringOffset = fbb.writeString(
          object.filesystemPathString,
        );
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.encryptedBool);
        fbb.addBool(2, object.pinnedBool);
        fbb.addOffset(3, fingerprintOffset);
        fbb.addInt64(4, object.index);
        fbb.addOffset(5, filesystemPathStringOffset);
        fbb.addOffset(6, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final encryptedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final pinnedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final fingerprintParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final indexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final filesystemPathStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = VaultEntity(
          id: idParam,
          encryptedBool: encryptedBoolParam,
          pinnedBool: pinnedBoolParam,
          fingerprint: fingerprintParam,
          index: indexParam,
          filesystemPathString: filesystemPathStringParam,
          name: nameParam,
        );

        return object;
      },
    ),
    WalletEntity: obx_int.EntityDefinition<WalletEntity>(
      model: _entities[5],
      toOneRelations: (WalletEntity object) => [],
      toManyRelations: (WalletEntity object) => {},
      getId: (WalletEntity object) => object.id,
      setId: (WalletEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WalletEntity object, fb.Builder fbb) {
        final addressOffset = fbb.writeString(object.address);
        final derivationPathOffset = fbb.writeString(object.derivationPath);
        final filesystemPathStringOffset = fbb.writeString(
          object.filesystemPathString,
        );
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.encryptedBool);
        fbb.addBool(2, object.pinnedBool);
        fbb.addOffset(3, addressOffset);
        fbb.addOffset(4, derivationPathOffset);
        fbb.addOffset(5, filesystemPathStringOffset);
        fbb.addOffset(6, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final encryptedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final pinnedBoolParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final addressParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final derivationPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final filesystemPathStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = WalletEntity(
          id: idParam,
          encryptedBool: encryptedBoolParam,
          pinnedBool: pinnedBoolParam,
          address: addressParam,
          derivationPath: derivationPathParam,
          filesystemPathString: filesystemPathStringParam,
          name: nameParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EthereumTransactionEntity] entity fields to define ObjectBox queries.
class EthereumTransactionEntity_ {
  /// See [EthereumTransactionEntity.id].
  static final id = obx.QueryIntegerProperty<EthereumTransactionEntity>(
    _entities[0].properties[0],
  );

  /// See [EthereumTransactionEntity.walletId].
  static final walletId = obx.QueryIntegerProperty<EthereumTransactionEntity>(
    _entities[0].properties[1],
  );

  /// See [EthereumTransactionEntity.creationDate].
  static final creationDate =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[2],
      );

  /// See [EthereumTransactionEntity.dbSignDataType].
  static final dbSignDataType =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[3],
      );

  /// See [EthereumTransactionEntity.amount].
  static final amount = obx.QueryStringProperty<EthereumTransactionEntity>(
    _entities[0].properties[4],
  );

  /// See [EthereumTransactionEntity.message].
  static final message = obx.QueryStringProperty<EthereumTransactionEntity>(
    _entities[0].properties[5],
  );

  /// See [EthereumTransactionEntity.contractAddress].
  static final contractAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[6],
      );

  /// See [EthereumTransactionEntity.senderAddress].
  static final senderAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[7],
      );

  /// See [EthereumTransactionEntity.recipientAddress].
  static final recipientAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[8],
      );

  /// See [EthereumTransactionEntity.signature].
  static final signature = obx.QueryStringProperty<EthereumTransactionEntity>(
    _entities[0].properties[9],
  );

  /// See [EthereumTransactionEntity.signDate].
  static final signDate = obx.QueryStringProperty<EthereumTransactionEntity>(
    _entities[0].properties[10],
  );

  /// See [EthereumTransactionEntity.fee].
  static final fee = obx.QueryStringProperty<EthereumTransactionEntity>(
    _entities[0].properties[11],
  );

  /// See [EthereumTransactionEntity.functionData].
  static final functionData =
      obx.QueryStringProperty<EthereumTransactionEntity>(
        _entities[0].properties[12],
      );
}

/// [GroupEntity] entity fields to define ObjectBox queries.
class GroupEntity_ {
  /// See [GroupEntity.id].
  static final id = obx.QueryIntegerProperty<GroupEntity>(
    _entities[1].properties[0],
  );

  /// See [GroupEntity.pinnedBool].
  static final pinnedBool = obx.QueryBooleanProperty<GroupEntity>(
    _entities[1].properties[1],
  );

  /// See [GroupEntity.encryptedBool].
  static final encryptedBool = obx.QueryBooleanProperty<GroupEntity>(
    _entities[1].properties[2],
  );

  /// See [GroupEntity.name].
  static final name = obx.QueryStringProperty<GroupEntity>(
    _entities[1].properties[3],
  );

  /// See [GroupEntity.filesystemPathString].
  static final filesystemPathString = obx.QueryStringProperty<GroupEntity>(
    _entities[1].properties[4],
  );
}

/// [NetworkGroupEntity] entity fields to define ObjectBox queries.
class NetworkGroupEntity_ {
  /// See [NetworkGroupEntity.id].
  static final id = obx.QueryIntegerProperty<NetworkGroupEntity>(
    _entities[2].properties[0],
  );

  /// See [NetworkGroupEntity.encryptedBool].
  static final encryptedBool = obx.QueryBooleanProperty<NetworkGroupEntity>(
    _entities[2].properties[1],
  );

  /// See [NetworkGroupEntity.pinnedBool].
  static final pinnedBool = obx.QueryBooleanProperty<NetworkGroupEntity>(
    _entities[2].properties[2],
  );

  /// See [NetworkGroupEntity.filesystemPathString].
  static final filesystemPathString =
      obx.QueryStringProperty<NetworkGroupEntity>(_entities[2].properties[3]);

  /// See [NetworkGroupEntity.name].
  static final name = obx.QueryStringProperty<NetworkGroupEntity>(
    _entities[2].properties[4],
  );

  /// See [NetworkGroupEntity.dbNetworkType].
  static final dbNetworkType = obx.QueryStringProperty<NetworkGroupEntity>(
    _entities[2].properties[5],
  );
}

/// [SolanaTransactionEntity] entity fields to define ObjectBox queries.
class SolanaTransactionEntity_ {
  /// See [SolanaTransactionEntity.id].
  static final id = obx.QueryIntegerProperty<SolanaTransactionEntity>(
    _entities[3].properties[0],
  );

  /// See [SolanaTransactionEntity.walletId].
  static final walletId = obx.QueryIntegerProperty<SolanaTransactionEntity>(
    _entities[3].properties[1],
  );

  /// See [SolanaTransactionEntity.creationDate].
  static final creationDate = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[2],
  );

  /// See [SolanaTransactionEntity.dbSignDataType].
  static final dbSignDataType =
      obx.QueryStringProperty<SolanaTransactionEntity>(
        _entities[3].properties[3],
      );

  /// See [SolanaTransactionEntity.amount].
  static final amount = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[4],
  );

  /// See [SolanaTransactionEntity.message].
  static final message = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[5],
  );

  /// See [SolanaTransactionEntity.contractAddress].
  static final contractAddress =
      obx.QueryStringProperty<SolanaTransactionEntity>(
        _entities[3].properties[6],
      );

  /// See [SolanaTransactionEntity.senderAddress].
  static final senderAddress = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[7],
  );

  /// See [SolanaTransactionEntity.recipientAddress].
  static final recipientAddress =
      obx.QueryStringProperty<SolanaTransactionEntity>(
        _entities[3].properties[8],
      );

  /// See [SolanaTransactionEntity.signature].
  static final signature = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[9],
  );

  /// See [SolanaTransactionEntity.signDate].
  static final signDate = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[10],
  );

  /// See [SolanaTransactionEntity.signerAddress].
  static final signerAddress = obx.QueryStringProperty<SolanaTransactionEntity>(
    _entities[3].properties[11],
  );

  /// See [SolanaTransactionEntity.transactionData].
  static final transactionData =
      obx.QueryStringProperty<SolanaTransactionEntity>(
        _entities[3].properties[12],
      );
}

/// [VaultEntity] entity fields to define ObjectBox queries.
class VaultEntity_ {
  /// See [VaultEntity.id].
  static final id = obx.QueryIntegerProperty<VaultEntity>(
    _entities[4].properties[0],
  );

  /// See [VaultEntity.encryptedBool].
  static final encryptedBool = obx.QueryBooleanProperty<VaultEntity>(
    _entities[4].properties[1],
  );

  /// See [VaultEntity.pinnedBool].
  static final pinnedBool = obx.QueryBooleanProperty<VaultEntity>(
    _entities[4].properties[2],
  );

  /// See [VaultEntity.fingerprint].
  static final fingerprint = obx.QueryStringProperty<VaultEntity>(
    _entities[4].properties[3],
  );

  /// See [VaultEntity.index].
  static final index = obx.QueryIntegerProperty<VaultEntity>(
    _entities[4].properties[4],
  );

  /// See [VaultEntity.filesystemPathString].
  static final filesystemPathString = obx.QueryStringProperty<VaultEntity>(
    _entities[4].properties[5],
  );

  /// See [VaultEntity.name].
  static final name = obx.QueryStringProperty<VaultEntity>(
    _entities[4].properties[6],
  );
}

/// [WalletEntity] entity fields to define ObjectBox queries.
class WalletEntity_ {
  /// See [WalletEntity.id].
  static final id = obx.QueryIntegerProperty<WalletEntity>(
    _entities[5].properties[0],
  );

  /// See [WalletEntity.encryptedBool].
  static final encryptedBool = obx.QueryBooleanProperty<WalletEntity>(
    _entities[5].properties[1],
  );

  /// See [WalletEntity.pinnedBool].
  static final pinnedBool = obx.QueryBooleanProperty<WalletEntity>(
    _entities[5].properties[2],
  );

  /// See [WalletEntity.address].
  static final address = obx.QueryStringProperty<WalletEntity>(
    _entities[5].properties[3],
  );

  /// See [WalletEntity.derivationPath].
  static final derivationPath = obx.QueryStringProperty<WalletEntity>(
    _entities[5].properties[4],
  );

  /// See [WalletEntity.filesystemPathString].
  static final filesystemPathString = obx.QueryStringProperty<WalletEntity>(
    _entities[5].properties[5],
  );

  /// See [WalletEntity.name].
  static final name = obx.QueryStringProperty<WalletEntity>(
    _entities[5].properties[6],
  );
}
