// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infra/entities/group_entity/group_entity.dart';
import 'infra/entities/network_group_entity/network_group_entity.dart';
import 'infra/entities/network_template_entity/embedded_network_template_entity.dart';
import 'infra/entities/transaction_entity/ethereum_transaction_entity.dart';
import 'infra/entities/transaction_entity/solana_transaction_entity.dart';
import 'infra/entities/vault_entity/vault_entity.dart';
import 'infra/entities/wallet_entity/wallet_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1774996566666262887),
      name: 'EmbeddedNetworkTemplateEntity',
      lastPropertyId: const obx_int.IdUid(9, 4136124407320652930),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7025979842183983582),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2889695118373630697),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 644748028817213181),
            name: 'addressEncoderType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4406444236889477175),
            name: 'derivationPathTemplate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5615877775262925084),
            name: 'derivatorType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8716687839791356098),
            name: 'dbCurveType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3918227823515093243),
            name: 'dbNetworkIconType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7287636458286131439),
            name: 'dbNetworkType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4136124407320652930),
            name: 'dbWalletType',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5889461611495230369),
      name: 'EthereumTransactionEntity',
      lastPropertyId: const obx_int.IdUid(13, 4086678592471639992),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8942720249562406608),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8526779378666861991),
            name: 'walletId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(1, 5815857230926402670)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7472142011631004640),
            name: 'creationDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 579939404191755247),
            name: 'dbSignDataType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8934118006750395043),
            name: 'amount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1235884691715924130),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5059213848707892441),
            name: 'contractAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6375860030626889437),
            name: 'senderAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 313469463859207839),
            name: 'recipientAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4914410254469345238),
            name: 'signature',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3850240698160088990),
            name: 'signDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6250986636446302546),
            name: 'fee',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4086678592471639992),
            name: 'functionData',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 1540742749332832753),
      name: 'GroupEntity',
      lastPropertyId: const obx_int.IdUid(5, 5821377126606120923),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4731000701272297772),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 877629658358681699),
            name: 'pinnedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6571732721339367678),
            name: 'encryptedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3782009884801433566),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5821377126606120923),
            name: 'filesystemPathString',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 3746926402829725407))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2409085661495747848),
      name: 'NetworkGroupEntity',
      lastPropertyId: const obx_int.IdUid(6, 6850140807544129749),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5670617246447766133),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7644042244757322608),
            name: 'encryptedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5081159682173217855),
            name: 'pinnedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2694218654459358694),
            name: 'filesystemPathString',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(3, 1225262591126719919)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2403889494550068949),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6850140807544129749),
            name: 'embeddedNetworkTemplateRelationId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 2715677212815006985),
            relationTarget: 'EmbeddedNetworkTemplateEntity')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4213015340856443009),
      name: 'SolanaTransactionEntity',
      lastPropertyId: const obx_int.IdUid(13, 1213694909643706931),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3270117083530724715),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1872301306318524909),
            name: 'walletId',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(5, 3119961423127491761)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8692915355876250524),
            name: 'creationDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2466070167724346391),
            name: 'dbSignDataType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6641596683088185436),
            name: 'amount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 40661573558621220),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1408459035942144317),
            name: 'contractAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8249695951803877777),
            name: 'senderAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 1122769616275460211),
            name: 'recipientAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7764968086502296534),
            name: 'signature',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 9100000372751011407),
            name: 'signDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4647511155473738773),
            name: 'signerAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1213694909643706931),
            name: 'transactionData',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 2675735059774266259),
      name: 'VaultEntity',
      lastPropertyId: const obx_int.IdUid(7, 2190379841135159501),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3727212209038245282),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1646770866136258555),
            name: 'encryptedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2503082705472956244),
            name: 'pinnedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8293869639426050623),
            name: 'fingerprint',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(6, 766510572278196614)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4648759422514694058),
            name: 'index',
            type: 6,
            flags: 8,
            indexId: const obx_int.IdUid(7, 4691426966708213695)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 319217413038332813),
            name: 'filesystemPathString',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(8, 3424096840970688228)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2190379841135159501),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 4789022395378864534),
      name: 'WalletEntity',
      lastPropertyId: const obx_int.IdUid(7, 364936521075446267),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3819551962649753253),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5363216954386559815),
            name: 'encryptedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8118378559770081650),
            name: 'pinnedBool',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8789915662918697124),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3984512483579054376),
            name: 'derivationPath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1015114016208198706),
            name: 'filesystemPathString',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(9, 751473337797489028)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 364936521075446267),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 4789022395378864534),
      lastIndexId: const obx_int.IdUid(9, 751473337797489028),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    EmbeddedNetworkTemplateEntity:
        obx_int.EntityDefinition<EmbeddedNetworkTemplateEntity>(
            model: _entities[0],
            toOneRelations: (EmbeddedNetworkTemplateEntity object) => [],
            toManyRelations: (EmbeddedNetworkTemplateEntity object) => {},
            getId: (EmbeddedNetworkTemplateEntity object) => object.id,
            setId: (EmbeddedNetworkTemplateEntity object, int id) {
              object.id = id;
            },
            objectToFB: (EmbeddedNetworkTemplateEntity object, fb.Builder fbb) {
              final nameOffset =
                  object.name == null ? null : fbb.writeString(object.name!);
              final addressEncoderTypeOffset = object.addressEncoderType == null
                  ? null
                  : fbb.writeString(object.addressEncoderType!);
              final derivationPathTemplateOffset =
                  object.derivationPathTemplate == null
                      ? null
                      : fbb.writeString(object.derivationPathTemplate!);
              final derivatorTypeOffset = object.derivatorType == null
                  ? null
                  : fbb.writeString(object.derivatorType!);
              final dbCurveTypeOffset = object.dbCurveType == null
                  ? null
                  : fbb.writeString(object.dbCurveType!);
              final dbNetworkIconTypeOffset = object.dbNetworkIconType == null
                  ? null
                  : fbb.writeString(object.dbNetworkIconType!);
              final dbNetworkTypeOffset = object.dbNetworkType == null
                  ? null
                  : fbb.writeString(object.dbNetworkType!);
              final dbWalletTypeOffset = object.dbWalletType == null
                  ? null
                  : fbb.writeString(object.dbWalletType!);
              fbb.startTable(10);
              fbb.addInt64(0, object.id);
              fbb.addOffset(1, nameOffset);
              fbb.addOffset(2, addressEncoderTypeOffset);
              fbb.addOffset(3, derivationPathTemplateOffset);
              fbb.addOffset(4, derivatorTypeOffset);
              fbb.addOffset(5, dbCurveTypeOffset);
              fbb.addOffset(6, dbNetworkIconTypeOffset);
              fbb.addOffset(7, dbNetworkTypeOffset);
              fbb.addOffset(8, dbWalletTypeOffset);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (obx.Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final nameParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
              final addressEncoderTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 8);
              final derivationPathTemplateParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 10);
              final derivatorTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 12);
              final dbCurveTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 14);
              final dbNetworkIconTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 16);
              final dbNetworkTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 18);
              final dbWalletTypeParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 20);
              final object = EmbeddedNetworkTemplateEntity(
                  id: idParam,
                  name: nameParam,
                  addressEncoderType: addressEncoderTypeParam,
                  derivationPathTemplate: derivationPathTemplateParam,
                  derivatorType: derivatorTypeParam,
                  dbCurveType: dbCurveTypeParam,
                  dbNetworkIconType: dbNetworkIconTypeParam,
                  dbNetworkType: dbNetworkTypeParam,
                  dbWalletType: dbWalletTypeParam);

              return object;
            }),
    EthereumTransactionEntity: obx_int.EntityDefinition<
            EthereumTransactionEntity>(
        model: _entities[1],
        toOneRelations: (EthereumTransactionEntity object) => [],
        toManyRelations: (EthereumTransactionEntity object) => {},
        getId: (EthereumTransactionEntity object) => object.id,
        setId: (EthereumTransactionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (EthereumTransactionEntity object, fb.Builder fbb) {
          final creationDateOffset = fbb.writeString(object.creationDate);
          final dbSignDataTypeOffset = object.dbSignDataType == null
              ? null
              : fbb.writeString(object.dbSignDataType!);
          final amountOffset =
              object.amount == null ? null : fbb.writeString(object.amount!);
          final messageOffset =
              object.message == null ? null : fbb.writeString(object.message!);
          final contractAddressOffset = object.contractAddress == null
              ? null
              : fbb.writeString(object.contractAddress!);
          final senderAddressOffset = object.senderAddress == null
              ? null
              : fbb.writeString(object.senderAddress!);
          final recipientAddressOffset = object.recipientAddress == null
              ? null
              : fbb.writeString(object.recipientAddress!);
          final signatureOffset = object.signature == null
              ? null
              : fbb.writeString(object.signature!);
          final signDateOffset = object.signDate == null
              ? null
              : fbb.writeString(object.signDate!);
          final feeOffset =
              object.fee == null ? null : fbb.writeString(object.fee!);
          final functionDataOffset = object.functionData == null
              ? null
              : fbb.writeString(object.functionData!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addOffset(2, creationDateOffset);
          fbb.addOffset(3, dbSignDataTypeOffset);
          fbb.addOffset(4, amountOffset);
          fbb.addOffset(5, messageOffset);
          fbb.addOffset(6, contractAddressOffset);
          fbb.addOffset(7, senderAddressOffset);
          fbb.addOffset(8, recipientAddressOffset);
          fbb.addOffset(9, signatureOffset);
          fbb.addOffset(10, signDateOffset);
          fbb.addOffset(11, feeOffset);
          fbb.addOffset(12, functionDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final creationDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final dbSignDataTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final amountParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final contractAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final senderAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final recipientAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final signatureParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final signDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final feeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final functionDataParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28);
          final object = EthereumTransactionEntity(
              id: idParam,
              walletId: walletIdParam,
              creationDate: creationDateParam,
              dbSignDataType: dbSignDataTypeParam,
              amount: amountParam,
              message: messageParam,
              contractAddress: contractAddressParam,
              senderAddress: senderAddressParam,
              recipientAddress: recipientAddressParam,
              signature: signatureParam,
              signDate: signDateParam,
              fee: feeParam,
              functionData: functionDataParam);

          return object;
        }),
    GroupEntity: obx_int.EntityDefinition<GroupEntity>(
        model: _entities[2],
        toOneRelations: (GroupEntity object) => [],
        toManyRelations: (GroupEntity object) => {},
        getId: (GroupEntity object) => object.id,
        setId: (GroupEntity object, int id) {
          object.id = id;
        },
        objectToFB: (GroupEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final filesystemPathStringOffset =
              fbb.writeString(object.filesystemPathString);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.pinnedBool);
          fbb.addBool(2, object.encryptedBool);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, filesystemPathStringOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final pinnedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final encryptedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final filesystemPathStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = GroupEntity(
              id: idParam,
              pinnedBool: pinnedBoolParam,
              encryptedBool: encryptedBoolParam,
              name: nameParam,
              filesystemPathString: filesystemPathStringParam);

          return object;
        }),
    NetworkGroupEntity: obx_int.EntityDefinition<NetworkGroupEntity>(
        model: _entities[3],
        toOneRelations: (NetworkGroupEntity object) =>
            [object.embeddedNetworkTemplateRelation],
        toManyRelations: (NetworkGroupEntity object) => {},
        getId: (NetworkGroupEntity object) => object.id,
        setId: (NetworkGroupEntity object, int id) {
          object.id = id;
        },
        objectToFB: (NetworkGroupEntity object, fb.Builder fbb) {
          final filesystemPathStringOffset =
              fbb.writeString(object.filesystemPathString);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.encryptedBool);
          fbb.addBool(2, object.pinnedBool);
          fbb.addOffset(3, filesystemPathStringOffset);
          fbb.addOffset(4, nameOffset);
          fbb.addInt64(5, object.embeddedNetworkTemplateRelation.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final encryptedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final pinnedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final filesystemPathStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = NetworkGroupEntity(
              id: idParam,
              encryptedBool: encryptedBoolParam,
              pinnedBool: pinnedBoolParam,
              filesystemPathString: filesystemPathStringParam,
              name: nameParam);
          object.embeddedNetworkTemplateRelation.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.embeddedNetworkTemplateRelation.attach(store);
          return object;
        }),
    SolanaTransactionEntity: obx_int.EntityDefinition<SolanaTransactionEntity>(
        model: _entities[4],
        toOneRelations: (SolanaTransactionEntity object) => [],
        toManyRelations: (SolanaTransactionEntity object) => {},
        getId: (SolanaTransactionEntity object) => object.id,
        setId: (SolanaTransactionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (SolanaTransactionEntity object, fb.Builder fbb) {
          final creationDateOffset = fbb.writeString(object.creationDate);
          final dbSignDataTypeOffset = object.dbSignDataType == null
              ? null
              : fbb.writeString(object.dbSignDataType!);
          final amountOffset =
              object.amount == null ? null : fbb.writeString(object.amount!);
          final messageOffset =
              object.message == null ? null : fbb.writeString(object.message!);
          final contractAddressOffset = object.contractAddress == null
              ? null
              : fbb.writeString(object.contractAddress!);
          final senderAddressOffset = object.senderAddress == null
              ? null
              : fbb.writeString(object.senderAddress!);
          final recipientAddressOffset = object.recipientAddress == null
              ? null
              : fbb.writeString(object.recipientAddress!);
          final signatureOffset = object.signature == null
              ? null
              : fbb.writeString(object.signature!);
          final signDateOffset = object.signDate == null
              ? null
              : fbb.writeString(object.signDate!);
          final signerAddressOffset = fbb.writeString(object.signerAddress);
          final transactionDataOffset = object.transactionData == null
              ? null
              : fbb.writeString(object.transactionData!);
          fbb.startTable(14);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.walletId);
          fbb.addOffset(2, creationDateOffset);
          fbb.addOffset(3, dbSignDataTypeOffset);
          fbb.addOffset(4, amountOffset);
          fbb.addOffset(5, messageOffset);
          fbb.addOffset(6, contractAddressOffset);
          fbb.addOffset(7, senderAddressOffset);
          fbb.addOffset(8, recipientAddressOffset);
          fbb.addOffset(9, signatureOffset);
          fbb.addOffset(10, signDateOffset);
          fbb.addOffset(11, signerAddressOffset);
          fbb.addOffset(12, transactionDataOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final walletIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final creationDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final signerAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final dbSignDataTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final amountParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final contractAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final senderAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final recipientAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final signDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 24);
          final signatureParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final transactionDataParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28);
          final object = SolanaTransactionEntity(
              id: idParam,
              walletId: walletIdParam,
              creationDate: creationDateParam,
              signerAddress: signerAddressParam,
              dbSignDataType: dbSignDataTypeParam,
              amount: amountParam,
              message: messageParam,
              contractAddress: contractAddressParam,
              senderAddress: senderAddressParam,
              recipientAddress: recipientAddressParam,
              signDate: signDateParam,
              signature: signatureParam,
              transactionData: transactionDataParam);

          return object;
        }),
    VaultEntity: obx_int.EntityDefinition<VaultEntity>(
        model: _entities[5],
        toOneRelations: (VaultEntity object) => [],
        toManyRelations: (VaultEntity object) => {},
        getId: (VaultEntity object) => object.id,
        setId: (VaultEntity object, int id) {
          object.id = id;
        },
        objectToFB: (VaultEntity object, fb.Builder fbb) {
          final fingerprintOffset = fbb.writeString(object.fingerprint);
          final filesystemPathStringOffset =
              fbb.writeString(object.filesystemPathString);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.encryptedBool);
          fbb.addBool(2, object.pinnedBool);
          fbb.addOffset(3, fingerprintOffset);
          fbb.addInt64(4, object.index);
          fbb.addOffset(5, filesystemPathStringOffset);
          fbb.addOffset(6, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final encryptedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final pinnedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final fingerprintParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final indexParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final filesystemPathStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = VaultEntity(
              id: idParam,
              encryptedBool: encryptedBoolParam,
              pinnedBool: pinnedBoolParam,
              fingerprint: fingerprintParam,
              index: indexParam,
              filesystemPathString: filesystemPathStringParam,
              name: nameParam);

          return object;
        }),
    WalletEntity: obx_int.EntityDefinition<WalletEntity>(
        model: _entities[6],
        toOneRelations: (WalletEntity object) => [],
        toManyRelations: (WalletEntity object) => {},
        getId: (WalletEntity object) => object.id,
        setId: (WalletEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WalletEntity object, fb.Builder fbb) {
          final addressOffset = fbb.writeString(object.address);
          final derivationPathOffset = fbb.writeString(object.derivationPath);
          final filesystemPathStringOffset =
              fbb.writeString(object.filesystemPathString);
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.encryptedBool);
          fbb.addBool(2, object.pinnedBool);
          fbb.addOffset(3, addressOffset);
          fbb.addOffset(4, derivationPathOffset);
          fbb.addOffset(5, filesystemPathStringOffset);
          fbb.addOffset(6, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final encryptedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final pinnedBoolParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final derivationPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final filesystemPathStringParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = WalletEntity(
              id: idParam,
              encryptedBool: encryptedBoolParam,
              pinnedBool: pinnedBoolParam,
              address: addressParam,
              derivationPath: derivationPathParam,
              filesystemPathString: filesystemPathStringParam,
              name: nameParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EmbeddedNetworkTemplateEntity] entity fields to define ObjectBox queries.
class EmbeddedNetworkTemplateEntity_ {
  /// See [EmbeddedNetworkTemplateEntity.id].
  static final id = obx.QueryIntegerProperty<EmbeddedNetworkTemplateEntity>(
      _entities[0].properties[0]);

  /// See [EmbeddedNetworkTemplateEntity.name].
  static final name = obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
      _entities[0].properties[1]);

  /// See [EmbeddedNetworkTemplateEntity.addressEncoderType].
  static final addressEncoderType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[2]);

  /// See [EmbeddedNetworkTemplateEntity.derivationPathTemplate].
  static final derivationPathTemplate =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[3]);

  /// See [EmbeddedNetworkTemplateEntity.derivatorType].
  static final derivatorType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[4]);

  /// See [EmbeddedNetworkTemplateEntity.dbCurveType].
  static final dbCurveType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[5]);

  /// See [EmbeddedNetworkTemplateEntity.dbNetworkIconType].
  static final dbNetworkIconType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[6]);

  /// See [EmbeddedNetworkTemplateEntity.dbNetworkType].
  static final dbNetworkType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[7]);

  /// See [EmbeddedNetworkTemplateEntity.dbWalletType].
  static final dbWalletType =
      obx.QueryStringProperty<EmbeddedNetworkTemplateEntity>(
          _entities[0].properties[8]);
}

/// [EthereumTransactionEntity] entity fields to define ObjectBox queries.
class EthereumTransactionEntity_ {
  /// See [EthereumTransactionEntity.id].
  static final id = obx.QueryIntegerProperty<EthereumTransactionEntity>(
      _entities[1].properties[0]);

  /// See [EthereumTransactionEntity.walletId].
  static final walletId = obx.QueryIntegerProperty<EthereumTransactionEntity>(
      _entities[1].properties[1]);

  /// See [EthereumTransactionEntity.creationDate].
  static final creationDate =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[2]);

  /// See [EthereumTransactionEntity.dbSignDataType].
  static final dbSignDataType =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[3]);

  /// See [EthereumTransactionEntity.amount].
  static final amount = obx.QueryStringProperty<EthereumTransactionEntity>(
      _entities[1].properties[4]);

  /// See [EthereumTransactionEntity.message].
  static final message = obx.QueryStringProperty<EthereumTransactionEntity>(
      _entities[1].properties[5]);

  /// See [EthereumTransactionEntity.contractAddress].
  static final contractAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[6]);

  /// See [EthereumTransactionEntity.senderAddress].
  static final senderAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[7]);

  /// See [EthereumTransactionEntity.recipientAddress].
  static final recipientAddress =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[8]);

  /// See [EthereumTransactionEntity.signature].
  static final signature = obx.QueryStringProperty<EthereumTransactionEntity>(
      _entities[1].properties[9]);

  /// See [EthereumTransactionEntity.signDate].
  static final signDate = obx.QueryStringProperty<EthereumTransactionEntity>(
      _entities[1].properties[10]);

  /// See [EthereumTransactionEntity.fee].
  static final fee = obx.QueryStringProperty<EthereumTransactionEntity>(
      _entities[1].properties[11]);

  /// See [EthereumTransactionEntity.functionData].
  static final functionData =
      obx.QueryStringProperty<EthereumTransactionEntity>(
          _entities[1].properties[12]);
}

/// [GroupEntity] entity fields to define ObjectBox queries.
class GroupEntity_ {
  /// See [GroupEntity.id].
  static final id =
      obx.QueryIntegerProperty<GroupEntity>(_entities[2].properties[0]);

  /// See [GroupEntity.pinnedBool].
  static final pinnedBool =
      obx.QueryBooleanProperty<GroupEntity>(_entities[2].properties[1]);

  /// See [GroupEntity.encryptedBool].
  static final encryptedBool =
      obx.QueryBooleanProperty<GroupEntity>(_entities[2].properties[2]);

  /// See [GroupEntity.name].
  static final name =
      obx.QueryStringProperty<GroupEntity>(_entities[2].properties[3]);

  /// See [GroupEntity.filesystemPathString].
  static final filesystemPathString =
      obx.QueryStringProperty<GroupEntity>(_entities[2].properties[4]);
}

/// [NetworkGroupEntity] entity fields to define ObjectBox queries.
class NetworkGroupEntity_ {
  /// See [NetworkGroupEntity.id].
  static final id =
      obx.QueryIntegerProperty<NetworkGroupEntity>(_entities[3].properties[0]);

  /// See [NetworkGroupEntity.encryptedBool].
  static final encryptedBool =
      obx.QueryBooleanProperty<NetworkGroupEntity>(_entities[3].properties[1]);

  /// See [NetworkGroupEntity.pinnedBool].
  static final pinnedBool =
      obx.QueryBooleanProperty<NetworkGroupEntity>(_entities[3].properties[2]);

  /// See [NetworkGroupEntity.filesystemPathString].
  static final filesystemPathString =
      obx.QueryStringProperty<NetworkGroupEntity>(_entities[3].properties[3]);

  /// See [NetworkGroupEntity.name].
  static final name =
      obx.QueryStringProperty<NetworkGroupEntity>(_entities[3].properties[4]);

  /// See [NetworkGroupEntity.embeddedNetworkTemplateRelation].
  static final embeddedNetworkTemplateRelation =
      obx.QueryRelationToOne<NetworkGroupEntity, EmbeddedNetworkTemplateEntity>(
          _entities[3].properties[5]);
}

/// [SolanaTransactionEntity] entity fields to define ObjectBox queries.
class SolanaTransactionEntity_ {
  /// See [SolanaTransactionEntity.id].
  static final id = obx.QueryIntegerProperty<SolanaTransactionEntity>(
      _entities[4].properties[0]);

  /// See [SolanaTransactionEntity.walletId].
  static final walletId = obx.QueryIntegerProperty<SolanaTransactionEntity>(
      _entities[4].properties[1]);

  /// See [SolanaTransactionEntity.creationDate].
  static final creationDate = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[2]);

  /// See [SolanaTransactionEntity.dbSignDataType].
  static final dbSignDataType =
      obx.QueryStringProperty<SolanaTransactionEntity>(
          _entities[4].properties[3]);

  /// See [SolanaTransactionEntity.amount].
  static final amount = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[4]);

  /// See [SolanaTransactionEntity.message].
  static final message = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[5]);

  /// See [SolanaTransactionEntity.contractAddress].
  static final contractAddress =
      obx.QueryStringProperty<SolanaTransactionEntity>(
          _entities[4].properties[6]);

  /// See [SolanaTransactionEntity.senderAddress].
  static final senderAddress = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[7]);

  /// See [SolanaTransactionEntity.recipientAddress].
  static final recipientAddress =
      obx.QueryStringProperty<SolanaTransactionEntity>(
          _entities[4].properties[8]);

  /// See [SolanaTransactionEntity.signature].
  static final signature = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[9]);

  /// See [SolanaTransactionEntity.signDate].
  static final signDate = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[10]);

  /// See [SolanaTransactionEntity.signerAddress].
  static final signerAddress = obx.QueryStringProperty<SolanaTransactionEntity>(
      _entities[4].properties[11]);

  /// See [SolanaTransactionEntity.transactionData].
  static final transactionData =
      obx.QueryStringProperty<SolanaTransactionEntity>(
          _entities[4].properties[12]);
}

/// [VaultEntity] entity fields to define ObjectBox queries.
class VaultEntity_ {
  /// See [VaultEntity.id].
  static final id =
      obx.QueryIntegerProperty<VaultEntity>(_entities[5].properties[0]);

  /// See [VaultEntity.encryptedBool].
  static final encryptedBool =
      obx.QueryBooleanProperty<VaultEntity>(_entities[5].properties[1]);

  /// See [VaultEntity.pinnedBool].
  static final pinnedBool =
      obx.QueryBooleanProperty<VaultEntity>(_entities[5].properties[2]);

  /// See [VaultEntity.fingerprint].
  static final fingerprint =
      obx.QueryStringProperty<VaultEntity>(_entities[5].properties[3]);

  /// See [VaultEntity.index].
  static final index =
      obx.QueryIntegerProperty<VaultEntity>(_entities[5].properties[4]);

  /// See [VaultEntity.filesystemPathString].
  static final filesystemPathString =
      obx.QueryStringProperty<VaultEntity>(_entities[5].properties[5]);

  /// See [VaultEntity.name].
  static final name =
      obx.QueryStringProperty<VaultEntity>(_entities[5].properties[6]);
}

/// [WalletEntity] entity fields to define ObjectBox queries.
class WalletEntity_ {
  /// See [WalletEntity.id].
  static final id =
      obx.QueryIntegerProperty<WalletEntity>(_entities[6].properties[0]);

  /// See [WalletEntity.encryptedBool].
  static final encryptedBool =
      obx.QueryBooleanProperty<WalletEntity>(_entities[6].properties[1]);

  /// See [WalletEntity.pinnedBool].
  static final pinnedBool =
      obx.QueryBooleanProperty<WalletEntity>(_entities[6].properties[2]);

  /// See [WalletEntity.address].
  static final address =
      obx.QueryStringProperty<WalletEntity>(_entities[6].properties[3]);

  /// See [WalletEntity.derivationPath].
  static final derivationPath =
      obx.QueryStringProperty<WalletEntity>(_entities[6].properties[4]);

  /// See [WalletEntity.filesystemPathString].
  static final filesystemPathString =
      obx.QueryStringProperty<WalletEntity>(_entities[6].properties[5]);

  /// See [WalletEntity.name].
  static final name =
      obx.QueryStringProperty<WalletEntity>(_entities[6].properties[6]);
}
